apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperclip-prod

resources:
  - ../../base

patches:
  - path: patches/resources.yaml
  - path: patches/config.yaml
  - path: patches/replicas.yaml
