apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperclip-user-passwords
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-backend
    kind: ClusterSecretStore
  target:
    name: paperclip-user-passwords
    creationPolicy: Owner
  data:
    - secretKey: rbanda@redhat.com
      remoteRef:
        key: secret/data/paperclip/users/rbanda
        property: password
    - secretKey: mlivings@redhat.com
      remoteRef:
        key: secret/data/paperclip/users/mlivings
        property: password
