apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperclip

resources:
  - namespace.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - paperclip-pvc.yaml
  - paperclip-deployment.yaml
  - paperclip-service.yaml
  - paperclip-route.yaml
  - paperclip-buildconfig.yaml
  - users-configmap.yaml
  - external-secret.yaml
  - provision-users-job.yaml
