apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: paperclip
spec:
  source:
    type: Binary
    binary: {}
    dockerfile: null
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: k8s/Dockerfile.openshift
  output:
    to:
      kind: ImageStreamTag
      name: paperclip:latest
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: paperclip
